# .github/workflows/deploy.yml
name: Deploy static site manually

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo (full history)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0               # Get all branches & history
          persist-credentials: true    # So we can push back

      # 2️⃣ Save current files (exclude .git and CI config)
      - name: Copy files to temp folder
        run: |
          mkdir temp-deploy
          rsync -av --exclude='.git' --exclude='.github' . temp-deploy/

      # 3️⃣ Configure git user
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 4️⃣ Switch to orphan gh-pages branch
      - name: Create gh-pages branch
        run: |
          git branch -D gh-pages || true
          git checkout --orphan gh-pages
          git rm -rf .                # remove all old files

      # 5️⃣ Copy back the saved site
      - name: Copy site into branch
        run: |
          rsync -av temp-deploy/ .

      # 6️⃣ Commit & push
      - name: Commit and push
        run: |
          git add .
          git commit -m "Deploy from main: $GITHUB_SHA"
          git push --force origin gh-pages

      # 7️⃣ Show URL
      - name: Print GitHub Pages URL
        run: |
          echo "🎉 Your site should be live at:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
